### ISSUE TITLE
smiley recognition

### ISSUE THREAD

**Issue by grindhold** [lukasepple/klammeraffe#2]
klammeraffe often overmotivatedly tends to autocomplete emoticons.

```
<grindhold>      So sad ... :(
<klammeraffe>    )
```

you could scan if an opening parenthesis/bracket/curly is part of the most common emoticons.

**Comment by sternenseemann** [comment]
Good point. Currently parsing of parenthesis happens character-wise but it is surely possible to do this.

**Comment by grindhold** [comment]
seems to work now

**Comment by sternenseemann** [comment]
Yesss, I just forgot this Issue :D
